CREATE DATABASE IF NOT EXISTS todo_app; 
 
USE todo_app; 
 
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY,     email VARCHAR(255) NOT NULL UNIQUE,     name VARCHAR(255),     provider VARCHAR(50) NOT NULL,     provider_id VARCHAR(255) NOT NULL,     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,     UNIQUE KEY unique_provider (provider, provider_id) ); 
 
CREATE TABLE IF NOT EXISTS tasks (id INT AUTO_INCREMENT PRIMARY KEY,     user_id INT NOT NULL,     title VARCHAR(255) NOT NULL,     description TEXT,     status ENUM('pending', 'in_progress', 'completed') DEFAULT 'pending',     due_date DATE,     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ); 